### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by payaldutta** [Ashish2030/Music-Hoster-FrontEnd-Using-React#11]
### What part(s) of the documentation would you like to see updated?

Description
Create Contributors Guideline to help new Contributors get started with this Project.

Additional Details
*Add a CONTRIBUTING.md to allow new users to get started with knowing how to contribute.
*Add Screenshots wherever possible.
*Add the basic information about creating Issues, Pull Requests and Branching.
*Mention tutorials related to Git and Github to help them better understand.

### Which Program are you part of?

- [x] DCP21
- [ ] Any other

**Comment by payaldutta** [comment]
@Ashish2030 I want to create Contributors Guidelines to help new Contributors get started with this Project.
Do assign me this under DCP'21.

**Comment by MukulKolpe** [comment]
There is already a file as CONTRIBUTING.md. But It will need an update. Make sure you make valid changes in the same file.
