### ISSUE TITLE
Highlighting section in navbar

### ISSUE THREAD

**Issue by Amrutha1101** [Ashish2030/Music-Hoster-FrontEnd-Using-React#15]
### **Describe the bug**
Highlighting which section is active in navbar

### Which Program are you part of?

- [x] DCP21
- [ ] Any other

**Comment by MukulKolpe** [comment]
Assigning @Amrutha1101 👍.
Make sure that you try to follow the theme of the project.
Before making the PR share the screenshots of the changes in our slack channel #music-hoster-application.
All the best!!

**Comment by MukulKolpe** [comment]
@Amrutha1101 any updates?

**Comment by AmruthaCK** [comment]
I'll make a PR today

**Comment by Amrutha1101** [comment]
I'll make a PR today
