### ISSUE TITLE
Scroll to top and custom scrollbar button 

### ISSUE THREAD

**Issue by HarshitPandey251** [Ashish2030/Music-Hoster-FrontEnd-Using-React#16]
### Is your feature request related to a problem? Please describe.
want to add Scroll to top button which help user to go top while in bottom of website

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Which Program are you part of?

- [x] DCP21 also LGMSOC'21
- [ ] Any other

**Comment by HarshitPandey251** [comment]
@MukulKolpe Pls assign this issue

**Comment by MukulKolpe** [comment]
Assigning @HarshitPandey251.
Before making a PR, please send a screen recording of the same in our slack channel.
All the best!!
